#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
