#!/bin/sh

update_master() {
  git fetch && git checkout -f origin/master
}

update_master
( cd fribidi && update_master ; )
( cd libass  && update_master ; )
( cd ffmpeg  && update_master ; )
( cd mpv     && update_master ; )

