#!/bin/sh
set -e

OPTIONS="--enable-gpl --enable-nonfree --enable-avresample --disable-debug --disable-doc"

BUILD="$(pwd)"
mkdir -p "$BUILD"/ffmpeg_build
cd "$BUILD"/ffmpeg_build
"$BUILD"/ffmpeg/configure --prefix="$BUILD"/build_libs --enable-static --disable-shared $OPTIONS
