#!/bin/sh
set -e
BUILD="$(pwd)"

OPTIONS=""

if "$BUILD"/scripts/test-libmpv ; then
    OPTIONS="$OPTIONS --with-pic"
fi

cd "$BUILD"/fribidi
./bootstrap
./configure --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --enable-static --disable-shared --without-glib $OPTIONS
