#!/bin/sh
set -e

OPTIONS=""

BUILD="$(pwd)"
cd "$BUILD"/libass
PKG_CONFIG_PATH="$BUILD"/build_libs/lib/pkgconfig ./autogen.sh --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --enable-static --disable-shared $OPTIONS
