#!/bin/sh
set -e

BUILD="$(pwd)"

if test -f "$BUILD"/mpv_options ; then
    set -- $(cat "$BUILD"/mpv_options) "$@"
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

# add missing private dependencies from libass.pc
# this is necessary due to the hybrid static / dynamic nature of the build
export LDFLAGS="$LDFLAGS $(pkg-config --libs fontconfig harfbuzz fribidi)"

echo Using mpv options: "$@"

cd "$BUILD"/mpv
python3 ./waf configure "$@"
