#!/bin/sh

# This script returns whether libmpv is to be built.

set -e

BUILD="$(pwd)"

USER_OPTS="$@"
if test -f "$BUILD"/mpv_options ; then
    grep -Eqe '--enable-libmpv|-Dlibmpv=true' "$BUILD"/mpv_options && exit 0
fi
exit 1
